export const portfolioSites = [
  {
    id: "SITE-CJK",
    name: "Cikarang Manufacturing Complex",
    type: "Manufacturing",
    power: 4.82,
    intensity: 318,
    costVariance: -4.2,
    savings: 1_146_000_000,
    opportunity: 904_000_000,
    alarms: 3,
    health: 98.4,
    state: "On target",
  },
  {
    id: "SITE-BTM",
    name: "Batam Edge Data Center",
    type: "Data Center",
    power: 3.47,
    intensity: 1.42,
    costVariance: 2.7,
    savings: 642_000_000,
    opportunity: 486_000_000,
    alarms: 1,
    health: 99.1,
    state: "Review",
  },
  {
    id: "SITE-SBY",
    name: "Surabaya Commercial Campus",
    type: "Commercial Campus",
    power: 2.21,
    intensity: 112,
    costVariance: -7.8,
    savings: 438_000_000,
    opportunity: 274_000_000,
    alarms: 0,
    health: 97.9,
    state: "On target",
  },
  {
    id: "SITE-MKS",
    name: "Makassar Cold Chain Hub",
    type: "Cold Storage",
    power: 1.86,
    intensity: 284,
    costVariance: 6.4,
    savings: 212_000_000,
    opportunity: 392_000_000,
    alarms: 2,
    health: 96.8,
    state: "Attention",
  },
];

export const actionItems = [
  {
    id: "ACT-8021",
    title: "Repair compressed-air leak on Line 4 header",
    asset: "COMP-04",
    owner: "Utility Maintenance",
    stage: "In Progress",
    due: "28 Jul 2026",
    estimated: 96_400_000,
    verified: 0,
    confidence: 94,
  },
  {
    id: "ACT-8018",
    title: "Sequence Chiller 1 and 2 using load bands",
    asset: "CH-01/02",
    owner: "HVAC Engineering",
    stage: "Approved",
    due: "04 Aug 2026",
    estimated: 240_000_000,
    verified: 0,
    confidence: 81,
  },
  {
    id: "ACT-8012",
    title: "Install occupancy setback for Heavy Lab AHU",
    asset: "AHU-HL-03",
    owner: "Facility Automation",
    stage: "Verification",
    due: "25 Jul 2026",
    estimated: 184_000_000,
    verified: 172_600_000,
    confidence: 91,
  },
  {
    id: "ACT-8009",
    title: "Restore automatic capacitor-bank control",
    asset: "MSB-02",
    owner: "Electrical Maintenance",
    stage: "Verified",
    due: "Completed",
    estimated: 68_200_000,
    verified: 71_400_000,
    confidence: 96,
  },
  {
    id: "ACT-8004",
    title: "Shift furnace preheat outside demand peak",
    asset: "FURN-A2",
    owner: "Production Planning",
    stage: "Validated",
    due: "02 Aug 2026",
    estimated: 312_500_000,
    verified: 0,
    confidence: 76,
  },
];

export const savingsLedger = [
  { initiative: "Power-factor correction", site: "Cikarang", energy: 28_400, saving: 71_400_000, payback: 2.7, confidence: 96, persistence: "Stable" },
  { initiative: "Boiler O₂ trim optimization", site: "Cikarang", energy: 142_800, saving: 286_000_000, payback: 1.4, confidence: 93, persistence: "Stable" },
  { initiative: "UPS eco-mode optimization", site: "Batam", energy: 186_200, saving: 244_000_000, payback: 0.8, confidence: 95, persistence: "Stable" },
  { initiative: "Campus HVAC scheduling", site: "Surabaya", energy: 121_600, saving: 188_000_000, payback: 1.1, confidence: 90, persistence: "Watch" },
  { initiative: "Cold-room door discipline", site: "Makassar", energy: 58_900, saving: 94_000_000, payback: 0.4, confidence: 87, persistence: "At risk" },
];

export const demandContributors = [
  { name: "Chiller 2", kw: 820, share: 18, deferrable: true },
  { name: "Compressor C-03", kw: 740, share: 16, deferrable: true },
  { name: "Production Line 2", kw: 690, share: 15, deferrable: false },
  { name: "Furnace A2", kw: 560, share: 12, deferrable: true },
  { name: "Other loads", kw: 1_800, share: 39, deferrable: false },
];

export const assets = [
  { id: "TX-01", type: "Transformer", location: "Main Substation", loading: 78, health: 92, capacity: 1.1, alarm: "Normal", maintenance: "42 days" },
  { id: "TX-02", type: "Transformer", location: "Process Substation", loading: 84, health: 86, capacity: 0.8, alarm: "Warning", maintenance: "18 days" },
  { id: "GEN-01", type: "Generator", location: "Utility Yard", loading: 12, health: 96, capacity: 2.2, alarm: "Normal", maintenance: "64 days" },
  { id: "CH-02", type: "Chiller", location: "Central Utility", loading: 81, health: 79, capacity: 0.4, alarm: "Warning", maintenance: "7 days" },
  { id: "COMP-04", type: "Compressor", location: "Line 4 Utility", loading: 71, health: 74, capacity: 0.3, alarm: "Attention", maintenance: "3 days" },
  { id: "BESS-01", type: "Battery", location: "Main Substation", loading: 36, health: 98, capacity: 1.5, alarm: "Normal", maintenance: "112 days" },
];

export const reports = [
  { name: "Executive Energy Performance", scope: "Enterprise", frequency: "Monthly", last: "01 Jul 2026", delivery: "6 recipients", status: "Ready" },
  { name: "Peak Demand & Cost Exposure", scope: "Cikarang", frequency: "Weekly", last: "21 Jul 2026", delivery: "4 recipients", status: "Ready" },
  { name: "Verified Savings Ledger", scope: "Enterprise", frequency: "Monthly", last: "01 Jul 2026", delivery: "8 recipients", status: "Ready" },
  { name: "Power Quality Investigation", scope: "Cikarang", frequency: "On event", last: "24 Jul 2026", delivery: "2 recipients", status: "Generated" },
  { name: "Tenant Billing Statement", scope: "Surabaya", frequency: "Monthly", last: "30 Jun 2026", delivery: "5 tenants", status: "Scheduled" },
  { name: "Data Completeness & Meter Health", scope: "Enterprise", frequency: "Daily", last: "25 Jul 2026", delivery: "3 recipients", status: "Ready" },
];

export const dataHealthRows = [
  { source: "PM-Main", type: "Power meter", connectivity: 100, freshness: "2 s", completeness: 100, sync: "Good", billing: "Ready", quality: "Good" },
  { source: "PM-MSB-02", type: "Power meter", connectivity: 100, freshness: "3 s", completeness: 99.8, sync: "Good", billing: "Ready", quality: "Good" },
  { source: "MTR-COMP-04", type: "Submeter", connectivity: 98.6, freshness: "18 s", completeness: 98.1, sync: "+0.8 s", billing: "Review", quality: "Stale" },
  { source: "GAS-BLR-01", type: "Gas meter", connectivity: 100, freshness: "14 s", completeness: 99.4, sync: "Good", billing: "Ready", quality: "Good" },
  { source: "STM-LINE-02", type: "Steam meter", connectivity: 94.2, freshness: "7 min", completeness: 91.8, sync: "+3.2 s", billing: "Blocked", quality: "Estimated" },
  { source: "MES-PROD", type: "MES integration", connectivity: 99.7, freshness: "32 s", completeness: 99.2, sync: "Good", billing: "N/A", quality: "Good" },
];
