/* eslint-disable */
// @ts-nocheck

// Generated by TanStack Router. Do not edit manually.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DataHealthRouteImport } from './routes/data-health'
import { Route as DemandRouteImport } from './routes/demand'
import { Route as ElectricalRouteImport } from './routes/electrical'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as IndexRouteImport } from './routes/index'

const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DataHealthRoute = DataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandRoute = DemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalRoute = ElectricalRouteImport.update({
  id: '/electrical',
  path: '/electrical',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/actions': typeof ActionsRoute
  '/alarms': typeof AlarmsRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/billing': typeof BillingRoute
  '/data-health': typeof DataHealthRoute
  '/demand': typeof DemandRoute
  '/electrical': typeof ElectricalRoute
  '/opportunities': typeof OpportunitiesRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/sustainability': typeof SustainabilityRoute
  '/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/actions': typeof ActionsRoute
  '/alarms': typeof AlarmsRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/billing': typeof BillingRoute
  '/data-health': typeof DataHealthRoute
  '/demand': typeof DemandRoute
  '/electrical': typeof ElectricalRoute
  '/opportunities': typeof OpportunitiesRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/sustainability': typeof SustainabilityRoute
  '/': typeof IndexRoute
}
export interface FileRoutesById {
  '__root__': typeof rootRouteImport
  '/actions': typeof ActionsRoute
  '/alarms': typeof AlarmsRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/billing': typeof BillingRoute
  '/data-health': typeof DataHealthRoute
  '/demand': typeof DemandRoute
  '/electrical': typeof ElectricalRoute
  '/opportunities': typeof OpportunitiesRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/sustainability': typeof SustainabilityRoute
  '/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/actions'
    | '/alarms'
    | '/analytics'
    | '/assets'
    | '/billing'
    | '/data-health'
    | '/demand'
    | '/electrical'
    | '/opportunities'
    | '/portfolio'
    | '/reports'
    | '/sustainability'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/actions'
    | '/alarms'
    | '/analytics'
    | '/assets'
    | '/billing'
    | '/data-health'
    | '/demand'
    | '/electrical'
    | '/opportunities'
    | '/portfolio'
    | '/reports'
    | '/sustainability'
    | '/'
  id:
    | '__root__'
    | '/actions'
    | '/alarms'
    | '/analytics'
    | '/assets'
    | '/billing'
    | '/data-health'
    | '/demand'
    | '/electrical'
    | '/opportunities'
    | '/portfolio'
    | '/reports'
    | '/sustainability'
    | '/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ActionsRoute: typeof ActionsRoute
  AlarmsRoute: typeof AlarmsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssetsRoute: typeof AssetsRoute
  BillingRoute: typeof BillingRoute
  DataHealthRoute: typeof DataHealthRoute
  DemandRoute: typeof DemandRoute
  ElectricalRoute: typeof ElectricalRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PortfolioRoute: typeof PortfolioRoute
  ReportsRoute: typeof ReportsRoute
  SustainabilityRoute: typeof SustainabilityRoute
  IndexRoute: typeof IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-health': {
      id: '/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof DataHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand': {
      id: '/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof DemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical': {
      id: '/electrical'
      path: '/electrical'
      fullPath: '/electrical'
      preLoaderRoute: typeof ElectricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ActionsRoute,
  AlarmsRoute,
  AnalyticsRoute,
  AssetsRoute,
  BillingRoute,
  DataHealthRoute,
  DemandRoute,
  ElectricalRoute,
  OpportunitiesRoute,
  PortfolioRoute,
  ReportsRoute,
  SustainabilityRoute,
  IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
